#!/usr/bin/env python


__author__ = "Kevin Vervloet"
__email__ = "kevin.vervloet@student.kdg.be"
__status__ = "Development"



def main():

sudo apt update && sudo apt upgrade


if __name__ == '__main__':  # run tests if called from command-line
    main()
